### ISSUE TITLE
Give feedback when the uploaded image exceeds the recommended size

### ISSUE THREAD

**Issue by darshitac11** [Atri-Labs/atrilabs-engine#100]
I was trying to upload an image from Unsplash that was 6.1MB. Either give feedback that it needs to be compressed or compress internally.

**Comment by cruxcode** [comment]
Agreed! Also, the current limit is 1MB for static assets. Do you think we should remove this limit?

**Comment by darshitac11** [comment]
Added resolution of this issue in the roadmap
