### ISSUE TITLE
Slider's position needs to be fixed in app - default top left corner

### ISSUE THREAD

**Issue by darshitac11** [Atri-Labs/atrilabs-engine#108]
![Screen Shot 2022-08-17 at 4 56 52 PM](https://user-images.githubusercontent.com/102641692/185241602-f64d8d4c-a461-4a8a-926c-af8c58caedca.png)
![Screen Shot 2022-08-17 at 4 57 11 PM](https://user-images.githubusercontent.com/102641692/185241656-be4411c4-d5ae-4eb2-8e2a-0ace05042e75.png)

**Comment by darshitac11** [comment]
Note the slider on top

**Comment by cruxcode** [comment]
implemented a new slider.
