### ISSUE TITLE
Slider's current position not directionally correct

### ISSUE THREAD

**Issue by darshitac11** [Atri-Labs/atrilabs-engine#109]
When the default value = max value, the current position marker should be at the right end.
![Screen Shot 2022-08-17 at 5 01 20 PM](https://user-images.githubusercontent.com/102641692/185242305-444ffde8-33c5-48ab-92f6-c4f04ba9f48d.png)
![Screen Shot 2022-08-17 at 5 01 29 PM](https://user-images.githubusercontent.com/102641692/185242348-4cc8171e-33f1-4120-a23d-f0214ae8cd1c.png)

**Comment by cruxcode** [comment]
Done! To be released in v0.0.48
