### ISSUE TITLE
Add zoom % so that full canvas is visible

### ISSUE THREAD

**Issue by darshitac11** [Atri-Labs/atrilabs-engine#110]
<img width="1437" alt="Screen Shot 2022-08-17 at 5 04 26 PM" src="https://user-images.githubusercontent.com/102641692/185242824-c611e09e-d796-46c9-9369-aed2f3122cdf.png">

**Comment by cruxcode** [comment]
Looking at the picture, it doesn't seem to be a scenario where zoom should kick in. The canvas acts closely like your website will behave in the currently selected screen size. If you see a scrollbar in the bottom, that means the content that you have put in canvas doesn't fit in 1000px width, hence, any screen smaller than 1000px will also show scrollbar.

The zoom effect in canvas is needed only when you want to see how the website will look in a screen size higher than yours. For example, assume you have 1000px screen, and you want to optimize the experience for users with 1400px screen, how will you be able to design 1400px in 1000px? The only way is to zoom-out (i.e. zoom less than 100%).

**Comment by darshitac11** [comment]
Got it, thanks for the explanation.
