### ISSUE TITLE
When to expect that saved changes in Python file will reflect in app?

### ISSUE THREAD

**Issue by darshitac11** [Atri-Labs/atrilabs-engine#114]

**Comment by cruxcode** [comment]
The saved changes in the python file may take a few seconds to reflect if all the code in the python file is correct. If the server finds any error in the python file, it won't reload the page with changes from python. 

For example, let's say you changed the color of the button to blue in python code but in the code editor, the color has been set to red. In scenarios where everything is correct in your python code, the button will appear blue, i.e. the changes from python take precedence. But if the python code ran into a problem/error, the button will appear red as set in the visual code editor. All the discussin in this paragraph assumes that you have written code inside `init_state` function.

I am keeping this post open till it resolves your doubt.
