### ISSUE TITLE
No change in the frontend when a value is provided to inputbox

### ISSUE THREAD

**Issue by darshitac11** [Atri-Labs/atrilabs-engine#120]
main.py
`from .atri import Atri
from fastapi import Request, Response

def init_state(at: Atri):
    at.bar1.custom.data = [
    {
        "x": "Book A",
        "reviews": 100000,
    },
    {
        "x": "Book B",
        "reviews": 50000,
    },
    {
        "x": "Book C",
        "reviews": 10000,
    },
    ]

def handle_page_request(at: Atri, req: Request, res: Response):
    pass 

def handle_event(at: Atri, req: Request, res: Response):
    if at.Input1.onChange:
        if at.Input1.custom.value == "1":
            at.bar1.custom.data = [
            {
                "x": "Book A",
                "reviews": 100000,
            },
            ]
        else:
            at.bar1.custom.data = [
            {
                "x": "Book A",
                "reviews": 100000,
            },
            {
                "x": "Book B",
                "reviews": 50000,
            },
            ]`

**Comment by darshitac11** [comment]
https://www.loom.com/share/cf4e2f219a3a4fd4a9c7ced5c2fcf10e

**Comment by cruxcode** [comment]
This issue has occured as we missed to add a `non-null` check in one of our recent commits. It has been fixed now.

**Comment by cruxcode** [comment]
You will have to set actions for `onChange` event of input component. I guess the action you would like to apply is `Send event data`.
