### ISSUE TITLE
Dropdown component not functional

### ISSUE THREAD

**Issue by darshitac11** [Atri-Labs/atrilabs-engine#122]
- Selected value not visible
- Available options not visible

https://www.loom.com/share/ad41405fcf6843a9a97271f4e68c6d74

**Comment by cruxcode** [comment]
Thanks for recording the video. It gave me clarity on the issue.

In dropdowns there are two different kinds of values:

1. value - sent to event listener
2. displayValue - only for end-users to see

For example, let's say we are listing products in the dropdown,  the `value` field will have `id` of the products and the `displayValue` field will have the name of the product.
