### ISSUE TITLE
How to address redundant components in Python?

### ISSUE THREAD

**Issue by darshitac11** [Atri-Labs/atrilabs-engine#125]
My app initially had a bar chart that I supplied value to through Python. Later, I came back to the editor and deleted the chart here. However, the Python file still contains the code I had written earlier. On publishing this edited app, I do not get any error. 

Should the user be educated that they need to remove redundant code from Python?

**Comment by cruxcode** [comment]
Are you talking about the `atri.py` file or `main.py` file?

**Comment by cruxcode** [comment]
Expected behavior.
