### ISSUE TITLE
keyboard shortcut for `Build & Run`

### ISSUE THREAD

**Issue by cruxcode** [Atri-Labs/atrilabs-engine#128]

**Comment by cruxcode** [comment]
A keyboard shortcut `Cmd + B` for macOS and `Ctri + B` for other OS should be used.

**Comment by harishfalco** [comment]
I can work on this @cruxcode .Please assign it me , if possible

**Comment by cruxcode** [comment]
In `packages/publish-app-layer/src/index.tsx`, you will find the "Build & Run" implementation. From the onClick event listener shown in the link below you can figure out what to do when the `Ctrl + B` is pressed.

https://github.com/Atri-Labs/atrilabs-engine/blob/main/packages/publish-app-layer/src/index.tsx#L62-L65

**Comment by LucidMach** [comment]
isn't more intuitive to simulate a click on the button on pressing `ctrl` + `b`

**Comment by cruxcode** [comment]
Done in PR #220
