### ISSUE TITLE
Add label with checkbox

### ISSUE THREAD

**Issue by darshitac11** [Atri-Labs/atrilabs-engine#157]

**Comment by Jitulteron7** [comment]
HI @darshitac11  mam. You are talking about the insert component checkbox ?

**Comment by cruxcode** [comment]
If you drag & drop a radio component, you will notice it has a label next to it. We want to do a similar implementation for the checkbox component. You find the code for Radio & Checkbox component in `packages/src/manifests` directory.

**Comment by Jitulteron7** [comment]
ok thanks

**Comment by Jitulteron7** [comment]
@cruxcode  is the project based on  micro frontend architecture?

**Comment by Jitulteron7** [comment]
@cruxcode is there any guideline for setup for this project

**Comment by cruxcode** [comment]
@Jitulteron7 no the project is not based on micro frontends architecture as of now. In future we might want to support multiple frontend frameworks, then we might think about microfrontends.

I would like to mention that our priority is on adding support for multiple backend languages. Currently, we only have Python.

**Comment by cruxcode** [comment]
@Jitulteron7 please have a look at the CONTRIBUTING.md https://github.com/Atri-Labs/atrilabs-engine/blob/main/CONTRIBUTING.md

**Comment by MuminAhmadKhan** [comment]
@darshitac11 Can I work on this ?

**Comment by 95871abhinandankumar** [comment]
can i work on this?

**Comment by MuminAhmadKhan** [comment]
![image](https://user-images.githubusercontent.com/63766734/190280240-cd239eed-c0c7-41d1-a953-2d2f3c1f7e9f.png)
Is this what was required ?

**Comment by cruxcode** [comment]
@MuminAhmadKhan the checkbox and the label `Checkbox` are not aligned vertically. It would be great if you can fix this.

**Comment by cruxcode** [comment]
> can i work on this?

@95871abhinandankumar I would request you to choose either #175 #176

**Comment by MuminAhmadKhan** [comment]
![image](https://user-images.githubusercontent.com/63766734/190322012-5cada4d7-d106-4139-9cfa-39eec3dcfdb2.png)
Is this right now ?

**Comment by cruxcode** [comment]
Yes, this seems correct. Please raise a PR.

**Comment by PansaraPriyanshi** [comment]
Can I work on this?

**Comment by cruxcode** [comment]
@PansaraPriyanshi please try some other good first issue.
