### ISSUE TITLE
Application for the Frontend developer role.

### ISSUE THREAD

**Issue by shashtag** [Atri-Labs/atrilabs-engine#177]
Till the time I saw the link for the job posting, it was closed.

Attaching my resume for a referral.

I am a freelance Fullstack developer. I have been working since the first year of my college. Products made by m have been use by lacs of people.

https://drive.google.com/file/d/1ON3ixRpPXuOXo0_8LFGys-923hbZLsh3/view?usp=drivesdk

**Comment by cruxcode** [comment]
Hi @shashtag,

Thanks for showing interest in working with us. Like all other applicants that come via different job platforms, we would like you to follow the steps below:

We are creating a full-stack web development framework to build Progressive Web Apps. It is open-source and available at https://github.com/Atri-Labs/atrilabs-engine.

:star:️ Star this repository if you find this framework helpful!

We are always actively hiring from our open-source community. Hence, for your assignment, you can pick any issue labeled as a “good first issue” here.
https://github.com/Atri-Labs/atrilabs-engine/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22

Follow the guidelines provided here to get started. https://github.com/Atri-Labs/atrilabs-engine/blob/main/CONTRIBUTING.md

If you have any questions or face any difficulties, ask us in GitHub Discussions or Issues. Our team is very responsive.

We hope that working on such an issue gives you a good understanding of what it is like to work in an open-source company.

NOTE: Any PR that you raise as part of the hiring process will not be used by Atri Labs apart for evaluating you.

**Comment by cruxcode** [comment]
If you are working on an issue in our GitHub repository, you can refer this video to understand how to add a React component in Atri framework. 

https://youtu.be/h3FNiiPZqpo
