### ISSUE TITLE
Add a Rating component

### ISSUE THREAD

**Issue by cruxcode** [Atri-Labs/atrilabs-engine#179]
The signature for the Rating component is as follows:

```typescript
export type RateProps = {
  styles: React.CSSProperties;
  custom: {
    // total number of stars
    total: number;
    // rating provided i.e. number of stars that appear colored
    rating: number;
    // color of the unrated star (default #C4C4C4)
    unratedColor: string;
    // color of rated star (default yellow)
    ratedColor: string;
  };
};

const Rate: React.FC<RateProps> = React.forwardRef((ref, props) => {
  return <div></div>;
})
```

The user interaction should be the same as in the ant design library as here https://ant.design/components/rate/

**Comment by cruxcode** [comment]
The steps to add a new component can be found in this discussion https://github.com/Atri-Labs/atrilabs-engine/pull/167

**Comment by Nikhil-Singh-Parmar** [comment]
> The steps to add a new component can be found in this discussion #167

Sir Can you please assign this to me ?

**Comment by Ayush-k-Shukla** [comment]
In PR 167 no such steps are mentioned.

**Comment by cruxcode** [comment]
> @cruxcode In PR 167 no such steps are mentioned. and also can you assign this to me.

Please look into discussion #169

**Comment by eransh1** [comment]
@cruxcode also can you please assign this project to me?

**Comment by cruxcode** [comment]
> @cruxcode do we have to make all the Rating types or any one will work?

Only the star one.

**Comment by cruxcode** [comment]
> @cruxcode also can you please assign this project to me?

Can you try to resolve #185 ?

**Comment by cruxcode** [comment]
Relevant discussions for this issue https://github.com/Atri-Labs/atrilabs-engine/discussions/169 https://github.com/Atri-Labs/atrilabs-engine/discussions/184 https://github.com/Atri-Labs/atrilabs-engine/discussions/180 https://github.com/Atri-Labs/atrilabs-engine/discussions/186 https://github.com/Atri-Labs/atrilabs-engine/discussions/187

**Comment by eransh1** [comment]
> > @cruxcode also can you please assign this project to me?
> 
> @eransh1 Can you try to resolve #185 ?

https://user-images.githubusercontent.com/110032464/190383083-fa5ee728-1327-4538-80e7-c3ed5ea8bba4.mp4

actually i was pretty much completed with this just doing final touch up , so can i do this one too?

**Comment by eransh1** [comment]
> @eransh1 okay go ahead with this. One question though, we want you to write the component from scratch without using the `ant-design` library or any other library.

i have used prop-types  and react-icon lib in this will that be acceptable?

**Comment by cruxcode** [comment]
@eransh1 yes those are acceptable. Go ahead and raise a PR.

**Comment by eransh1** [comment]
> @eransh1 yes those are acceptable. Go ahead and raise a PR.

@cruxcode i have made my component using only javascript and css but it seems you required typescript, but i dont have any knowledge or experience in typescript so will that be acceptable too?
sorry for lot of questions , i am a fresher in this.

**Comment by cruxcode** [comment]
@eransh1 , our entire codebase is in Typescript. We would like to see if you can translate it in Typescript.

**Comment by eransh1** [comment]
> @eransh1 , our entire codebase is in Typescript. We would like to see if you can translate it in Typescript.

okay thanks, will try .

**Comment by niteshmodi** [comment]
Hey can you assign it to me?

**Comment by vamsirevada** [comment]
Can you assign it to me i do want to work on it?

**Comment by darshitac11** [comment]
@all-contributors please add @vamsirevada , @Ayush-k-Shukla  for userTesting

**Comment by darshitac11** [comment]
@all-contributors please add @Ayush-k-Shukla for userTesting

**Comment by darshitac11** [comment]
@all-contributors please add @Nikhil-Singh-Parmar  for userTesting

**Comment by darshitac11** [comment]
@all-contributors please add @aryans1319  for userTesting

**Comment by darshitac11** [comment]
@all-contributors please add @eransh1  for userTesting

**Comment by darshitac11** [comment]
@all-contributors please add @niteshmodi  for userTesting
