### ISSUE TITLE
Add Alert Component

### ISSUE THREAD

**Issue by cruxcode** [Atri-Labs/atrilabs-engine#185]
Component Signature:

```typescript
export type AlertProps = {
  styles: React.CSSProperties;
  custom: {
    title: string;
    description?: string;
    statusIcon?: string;
  };
};

export const Alert: React.FC<AlertProps> = React.forwardRef((ref, props) => {
  return <div></div>;
});
```

Hint for custom props:
```typescript
const customTreeOptions: CustomPropsTreeOptions = {
  dataTypes: {
    title: "text",
    description: "text",
    statusIcon: "static_asset",
  },
};
```
![Screen Shot 2022-09-15 at 2 14 29 PM](https://user-images.githubusercontent.com/30747788/190358540-17ab67f9-5cfc-489f-b85f-fbeebbb72d47.png)

**Comment by cruxcode** [comment]
Relevant discussions for this issue #169 #184

**Comment by jonathanalvares9009** [comment]
Hi @cruxcode, could you assign me this issue please?

**Comment by PansaraPriyanshi** [comment]
Can I work on thi issue?

**Comment by jonathanalvares9009** [comment]
Hi @cruxcode, why do we need a static asset field. Can we not use material-ui library for this?

**Comment by arjundubey-cr** [comment]
hi @cruxcode I would like to work on this issue

**Comment by shashtag** [comment]
Hey! @cruxcode can you please assign me this issue.

**Comment by Am10aN16** [comment]
Hey can u please assign me this issue

**Comment by Mahe9041** [comment]
Hi @cruxcode, could you assign me this issue please?

**Comment by SurajPhulara** [comment]
Hey @cruxcode can u please assign me this issue.

**Comment by sahilsuman933** [comment]
@cruxcode can I work on this issue?

**Comment by darshitac11** [comment]
@all-contributors please add @PansaraPriyanshi for userTesting

**Comment by darshitac11** [comment]
@all-contributors please add @shashtag for userTesting

**Comment by darshitac11** [comment]
@all-contributors please add @Am10aN16 for userTesting

**Comment by darshitac11** [comment]
@all-contributors please add @Mahe9041  for userTesting

**Comment by darshitac11** [comment]
@all-contributors please add @sahilsuman933 for userTesting

**Comment by jonathanalvares9009** [comment]
This issue is not yet resolved

**Comment by jonathanalvares9009** [comment]
## TODO

- [ ] Solve #462 
- [ ] Create a photo alert component 
- [ ] Test the alert component
