### ISSUE TITLE
a small update to CONTRIBUTING.md

### ISSUE THREAD

**Issue by LucidMach** [Atri-Labs/atrilabs-engine#204]
sorta confused about where to run `lerna bootstrap`
esp cuz the previous command `rm -rf $PROJECT_ROOT/node_modules` changes the **cwd**

assuming that doesn't really matter
ended up `cd`ing to _project home_ dir

**Comment by darshitac11** [comment]
@LucidMach - thanks for raising this issue. 

However, since it doesn't matter where you are inside the `project home`, we can leave the CONTRIBUTING.md unchanged for now. 

We are planning to migrate form `lerna` to `turborepo` soon. So these steps will have to rewritten anyways.
