### ISSUE TITLE
Add Tooltip in the top panel of visual editor

### ISSUE THREAD

**Issue by darshitac11** [Atri-Labs/atrilabs-engine#212]
Attached image for reference 
![tooltip](https://user-images.githubusercontent.com/102641692/191112429-56c438ee-cebb-4719-8eaf-c5290b460207.png)

**Comment by harishfalco** [comment]
Please assign it to me @darshitac11 , @cruxcode .

**Comment by harishfalco** [comment]
On it.

**Comment by darshitac11** [comment]
The three panels appear in order form left to right:

- Style panel 
- Custom panel
- Actions panel

Does that answer your question? Else, I can update the picture

**Comment by harishfalco** [comment]
Thanks @darshitac11 .Can you also help me to find the file where I can add tooltips for these?I tried searching for it ,but couldn't find it.

**Comment by darshitac11** [comment]
Sure! 

I don't have it handy but I'll search for it and share here soon :)

**Comment by cruxcode** [comment]
Done in PR #220
