### ISSUE TITLE
Scroll when Actions panel is open results in flickering effect

### ISSUE THREAD

**Issue by darshitac11** [Atri-Labs/atrilabs-engine#215]
Scrolling the contents on the canvas results in flickering effect if the actions panel is open. It is immediately resolved once the panel is closed. 

Attached video for reference - 
https://www.loom.com/share/c00f35401f1f4a028f5f974e1cdcec36

**Comment by factscub** [comment]
can i work on this ?

**Comment by cruxcode** [comment]
@factscub please pick an issue from good first issue

**Comment by darshitac11** [comment]
@factscub - please pick an issue from this list.

**Comment by factscub** [comment]
could you assign me this task ?

**Comment by darshitac11** [comment]
@factscub - Sorry I forgot to link the list of issues that you can pick from. Here it is - https://github.com/Atri-Labs/atrilabs-engine/labels/good%20first%20issue

We have marked several issues as “good first issues” which are suitable to newcomers.
