### ISSUE TITLE
Height & width Parameter not resetting after being removed

### ISSUE THREAD

**Issue by sanskarg348** [Atri-Labs/atrilabs-engine#219]

**Comment by sahilsuman933** [comment]
Hey @sanskarg348, could you please provide some description of this bug?

**Comment by sanskarg348** [comment]
Okay sure,

When height/width is provided for any component and if afterwards the height parameter is no longer needed, when it is removed the height/width stands 0 or None it doesn't reset to default as it was before providing the height/width.

**Comment by darshitac11** [comment]
@sahilsuman933 - if you are interested in working on an open issue, please pick one from this list. They are suitable for newcomers - https://github.com/Atri-Labs/atrilabs-engine/labels/good%20first%20issue

**Comment by sahilsuman933** [comment]
Most of the issues are already assigned to someone else @darshitac11

**Comment by darshitac11** [comment]
That's okay. We are assigning same issue to multiple people and you can work independently on it. 

Let us know which issue you would like to work on.

**Comment by sahilsuman933** [comment]
Okay, @darshitac11 .

**Comment by adityaxpique** [comment]
The mentioned issue has been resolved.

**Comment by darshitac11** [comment]
@all-contributors please add @sanskarg348  for contributing bug report, doc, code, example, promotion, video
