### ISSUE TITLE
Create a to-do list web app

### ISSUE THREAD

**Issue by darshitac11** [Atri-Labs/atrilabs-engine#234]
Instructions for this issue:

1. Build a to-do list web app using Atri framework. 
- This app should be responsive. 
- You can pick any design. 
- Follow the instructions provided [here](https://github.com/Atri-Labs/atrilabs-engine/blob/main/CONTRIBUTING.md#creating-an-atri-app) to create an Atri app.
- You can also refer [this YouTube playlist](https://www.youtube.com/watch?v=p135tfBvdaE&list=PLTQwOMNg4n8CJf2mbF5pJ3A9cEjr1gdRf)

2. Write its backend using Python to:
- add or remove tasks
- strikethrough to indicate completion

3. Deploy your app using GitHub pages and Atri CLI. You can follow the steps here https://docs.atrilabs.com/deploy-app/deploy-ghpages 

4. Submit a Pull Request (PR).
- Once your PR is merged, your app will be added to the [made-with-atri folder](https://github.com/Atri-Labs/atrilabs-engine/blob/main/made-with-atri/README.md).

**Comment by Soumyajit2825** [comment]
@darshitac11 i want to contribute in it.

**Comment by darshitac11** [comment]
@Soumyajit2825 - you can pick any design for the app and have as many functionalities as you like.

**Comment by darshitac11** [comment]
@Soumyajit2825 - It is a responsive web app. 

Apologies for the lack of details.

**Comment by darshitac11** [comment]
@Soumyajit2825 - I have updated the description. Hope that helps!

**Comment by tenserebel** [comment]
Hello, can I help with this?

**Comment by darshitac11** [comment]
Yes, sure. Assigned the task to you. 

Let us know if you need any help or have any questions.

**Comment by tenserebel** [comment]
> Yes, sure. Assigned the task to you.
> 
> Let us know if you need any help or have any questions.

Yes, I have a question is there a way to dynamically create components such as textbox or checkbox when a button is clicked (through onclick)?

**Comment by darshitac11** [comment]
Yes - just how it works in other frameworks, you can add a textbox/checkbox inside a flexbox. Set "display = none" initially and from backend, set "display = flex" when a button is clicked. 

Example code below:

https://github.com/Atri-Apps/atri-landing/blob/ce194c9a06edf19f3f4da41c9914b4a338a5c254/controllers/routes/main.py#L26-L28

**Comment by tenserebel** [comment]
hello, I am having issue with github page deploymet, but I have uploaded it on github, could you suggest a solution for this?

https://github.com/tenserebel/TrackDash---Using-Atri

**Comment by tenserebel** [comment]
Hello, any updates regarding the above mentioned query?

**Comment by cruxcode** [comment]
Hi @tenserebel, can you tell me which operating system you are using? To deploy to Github, you might have to use different commands in windows and macOS, especially, the commands to set an environment variable.

**Comment by tenserebel** [comment]
> Hi @tenserebel, can you tell me which operating system you are using? To deploy to Github, you might have to use different commands in windows and macOS, especially, the commands to set an environment variable.

Hello, I am using windows, could you help me setting that up?

**Comment by cruxcode** [comment]
I am assuming you are using cmd in windows.

### Build steps:

```
cd project_root
pipenv shell
set MODE=production
set ASSET_URL_PREFIX="/TrackDash---Using-Atri"
atri build ssg
```

### Deploy steps:

```
set GIT_USER=tenserebel
atri deploy ssg --gh-pages
```

**Comment by tenserebel** [comment]
Hello @cruxcode, Once I commented out this part of the code, it was able to work. On line number 98.
![image](https://user-images.githubusercontent.com/63343297/225736532-4a433f1e-fca4-412b-b559-2cbf569d8c65.png)


But, the deployed version doesn't work properly: https://tenserebel.github.io/TrackDash---Using-Atri/

**Comment by tenserebel** [comment]
Hello I have made a pr to close this issue. [https://github.com/Atri-Labs/atrilabs-engine/pull/733](PR)

@cruxcode @darshitac11
