### ISSUE TITLE
undo-redo doesn't work in certain scenario

### ISSUE THREAD

**Issue by cruxcode** [Atri-Labs/atrilabs-engine#243]
In the new version v0.0.65 you might have to undo more than once for some kinds of actions:

### Completed
1. If you drop a new component.
2. If you copy and paste a component.
3. If you create a component from a template.
4. Spacing property, size property. etc.

### Parked
1. Batch undo when dragging in position or spacing.

### Not related to undo-redo
1. If you change the background color.

The undo works as expected when the user takes actions such as:

1. Repositions of a component
2. Changes some properties (except background color) from the styles panel or custom panel

[Undo-Redo Problems.pdf](https://github.com/Atri-Labs/atrilabs-engine/files/9760996/Undo-Redo.Problems.pdf)

**Comment by darshitac11** [comment]
@all-contributors please add @cruxcode  for adding bug report

**Comment by cruxcode** [comment]
We need to check if a series of activity can be undo-redo properly.
