### ISSUE TITLE
Create a URL Shortener App

### ISSUE THREAD

**Issue by darshitac11** [Atri-Labs/atrilabs-engine#244]
Instructions for this issue:

1. Build a URL Shortener web app using Atri framework. 
- This app should be responsive. 
- You can pick any design. 
- You can refer [this tutorial](https://www.freecodecamp.org/news/python-tutorial-how-to-create-a-url-shortener-using-flask/).
- Follow the instructions provided [here](https://github.com/Atri-Labs/atrilabs-engine/blob/main/CONTRIBUTING.md#creating-an-atri-app) to create an Atri app.
- You can also refer [this YouTube playlist](https://www.youtube.com/watch?v=p135tfBvdaE&list=PLTQwOMNg4n8CJf2mbF5pJ3A9cEjr1gdRf)

2. Write its backend using Python to:
- take a long URL and generate a shorter version

3. Deploy your app using GitHub pages and Atri CLI. You can follow the steps here https://docs.atrilabs.com/deploy-app/deploy-ghpages 

4. Submit a Pull Request (PR).
- Once your PR is merged, your app will be added to the [made-with-atri folder](https://github.com/Atri-Labs/atrilabs-engine/blob/main/made-with-atri/README.md).

**Comment by JadhavSankalp7** [comment]
Hello, I am Sankalp Jadhav.
I want to work on this. 
Could you assign me?

**Comment by darshitac11** [comment]
Hi @JadhavSankalp7,

I have assigned this issue to you. Let us know if you face any difficulty. We are active here and on [Slack](https://join.slack.com/t/atricommunity/shared_invite/zt-1e756m1at-bZBxngvw7KWWO0riI4pc0w).

**Comment by JadhavSankalp7** [comment]
Yes Ma'am, I am Final Year Student. We are having Lab Project in Open Source Contribution. 
I will contact you if I am in some doubt.

**Comment by darshitac11** [comment]
@all-contributors please add @JadhavSankalp7 for userTesting

**Comment by JadhavSankalp7** [comment]
Hello Ma'am I not understanding the UI of the framework. Also I am not able to how to delete selected elements.

**Comment by JadhavSankalp7** [comment]
Ma'am How do I Resize Components?

**Comment by darshitac11** [comment]
To learn about resizing components and the framework more generally, watch the [video tutorials in this playlist](https://www.youtube.com/watch?v=p135tfBvdaE&list=PLTQwOMNg4n8CJf2mbF5pJ3A9cEjr1gdRf). 

To learn about repositioning, refer [this video tutorial](https://www.youtube.com/watch?v=Lrcd0I8dgQU). 

[This discussion ](https://github.com/Atri-Labs/atrilabs-engine/discussions/241) has other productivity tips.

**Comment by JadhavSankalp7** [comment]
Ma'am, I have made the front end. 
I am not able to add functionalities to the components in the back end.

**Comment by darshitac11** [comment]
@JadhavSankalp7 - if you need help in understanding backend, you can refer [this video tutorial](https://www.youtube.com/watch?v=i258mksEdT8). You can also watch [the entire playlist ](https://www.youtube.com/watch?v=p135tfBvdaE&list=PLTQwOMNg4n8CJf2mbF5pJ3A9cEjr1gdRf)for more context. 

You can also ask us questions in our [Slack community](https://join.slack.com/t/atricommunity/shared_invite/zt-1e756m1at-bZBxngvw7KWWO0riI4pc0w) so that we may guide you. 

Let me know if this sounds feasible to you.

**Comment by JadhavSankalp7** [comment]
I want help regarding linking back end code to front end components.

**Comment by darshitac11** [comment]
Any component can be accessed in the backend by writing at.<component name> in `controllers/routes/main.py` file. 

[Docs](https://docs.atrilabs.com/getting-started/create-app#creating-backend-of-the-app) has additional details.

**Comment by darshitac11** [comment]
[This video tutorial](https://youtu.be/i258mksEdT8) covers backend development using Atri framework. This should be helpful.

**Comment by JadhavSankalp7** [comment]
Ma'am, I referred the video. I found it helpful. 

I want to know how to take input from front end components and process the inputs in the backend with code.

**Comment by darshitac11** [comment]
Let us take button component as an example. Suppose the text on it is set to `Submit` through the visual editor.
 
If you want to access this text in backend and modify it, you can write:

```
    # Access text and store in a variable
    text_val = at.Button11.custom.text

    # Modify the variable
    text_val = "Modified text"

    # Reassign text to component
    at.Button11.custom.text = text_val
```

**Comment by darshitac11** [comment]
If you can share the specific component you need help with, let me know.

In the meantime, you can create Pull Request for the work done so far.

**Comment by JadhavSankalp7** [comment]
https://github.com/JadhavSankalp7/URL_SHORTENER
Maam, this is what I have made so far.

**Comment by JadhavSankalp7** [comment]
Hello Ma'am, How to take input from "Input Component" and process it in the backend? and to add functionality to Submit Button and Display the result?

**Comment by darshitac11** [comment]
@JadhavSankalp7 - please refer this video: https://www.loom.com/share/a21dbdbd3aa6420c89c854c30f22af6f

In this video, I have added an `Inputbox` where users enter a value and click on the `Button`. This changes the text displayed in the `Textbox`. 

You don't need to remember the API - as you press `.`, you get all available options.

The code is as follows: 

```
def handle_event(at: Atri, req: Request, res: Response):
    
    # Take value from Inputbox
    val = at.Input1.custom.value

    # Modify the value in backend
    modified_val = val + ' 2022'

    # Check if the button is clicked
    if at.Button2.onClick:

        # Change the text displayed in textbox
        at.TextBox1.custom.text = modified_val
    pass
```

**Comment by JadhavSankalp7** [comment]
File "c:\Users\Sankalp\URL_SHORTENER\controllers\routes\main.py", line 1, in <module>
    from .atri import Atri
ImportError: attempted relative import with no known parent package. 
Ma'am I am getting this error.

**Comment by JadhavSankalp7** [comment]
Ma'am I made the backend. I want to deploy the project.  I am having doubts on how to deploy the project. How do I deploy using Docker?

**Comment by JadhavSankalp7** [comment]
Ma'am How do I put a Pull Request?

**Comment by darshitac11** [comment]
@JadhavSankalp7 - refer this official guide by GitHub: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by JadhavSankalp7** [comment]
Ma'am I created the pull request.
And Can you review it?

I am get difficulty with deployment of the app.
