### ISSUE TITLE
Add a Testimonials Component

### ISSUE THREAD

**Issue by adityaxpique** [Atri-Labs/atrilabs-engine#256]
The signature of testimonials component should be as follows:-  

```
type TestimonialProps = {
 // Time in milliseconds for each slide
 intervalTime?: number;
 items: {
   // Image of the person giving the review
   profileImage: string;
   // Name of the person giving the review
   profileName: string;
   // The review
   text: string;
   // The designation of review giver
   designation: string
   // The rating
   rating: number
 }[];
};
 
export const Testimonial: React.FC<TestimonialProps> = React.forwardRef(
  (ref, props) => {
    return <div></div>;
  }
);

```

Design Reference - https://webflow.com/made-in-webflow/website/Testimonial-Component-25

**Comment by Naveen-Nair** [comment]
Hey! I'm interested to contribute to this project. Can you assign me to this task?

**Comment by darshitac11** [comment]
@Naveen-Nair - great! I have assigned this issue to you. 

Let us know if you have any questions here or in our [Slack community](https://join.slack.com/t/atricommunity/shared_invite/zt-1e756m1at-bZBxngvw7KWWO0riI4pc0w).

**Comment by darshitac11** [comment]
@all-contributors please add @Naveen-Nair for userTesting

**Comment by vikyale** [comment]
Hello! I'd like to help in this issue, can you assign me to this task?  :)

**Comment by darshitac11** [comment]
Done!
