### ISSUE TITLE
Add a Badge Component

### ISSUE THREAD

**Issue by adityaxpique** [Atri-Labs/atrilabs-engine#264]
The signature of badge component should be as follows:-
```

type BadgeProps = {
       styles: React.CSSProperties;
       custom: { 
                //The child to show inside the box. The user can drag and drop it into the box to apply it(like you can drag and drop 
                components into flexbox).
		child: React.ReactNode[];
		//The max number you show above the box.
		maxLimit: number;
		//Sets the badge as status dot;
		isStatus: boolean;
		//The text that gets displays when you hover over the badge
		tooltip: string;
		//The amount of offset in the x and y axis.
		offset: [number, number];
		//The color of the dot
		color: string;
		//The number to show in the badge
		count: number;
       };
};
 
export const BadgeProps: React.FC<BadgeProps> = React.forwardRef(
  (ref, props) => {
    return <div></div>;
  }
);
```
![8](https://user-images.githubusercontent.com/56078748/194698179-d61eb71a-5287-451c-b19b-48c707c20920.png)

![7](https://user-images.githubusercontent.com/56078748/194698174-7d8e9601-be71-40b3-9201-6d60e5f49213.png)

**Comment by Potato-29** [comment]
Hi @adityaxpique , I'd like to build this component, can you assign it for me?

**Comment by darshitac11** [comment]
Done! Your username is hilarious by the way @Potato-29 😆

**Comment by Potato-29** [comment]
Haha thanks XD I'll start working now then.

**Comment by Potato-29** [comment]
ah hey really sorry to bail out but I realized in the end that it's python and I'm really good with, but thanks for giving me a chance :)

**Comment by darshitac11** [comment]
Sure, no problem.

**Comment by darshitac11** [comment]
@all-contributors please add @Potato-29 for userTesting

**Comment by Potato-29** [comment]
> Sure, no problem.
> 
> However, this issue only requires knowledge of Typescript and React.

Wait is that so? I saw python and was overwhelmed, I'll give it another shot then and btw thanks for adding me as a tester in contributors :)

**Comment by darshitac11** [comment]
@Potato-29 since our repo follows [all-contributors](https://allcontributors.org/) specification, both no-code and code contributions are celebrated and featured in our README. 💖

**Comment by vikyale** [comment]
Hello! I'd like to help in this issue :)

**Comment by factscub** [comment]
Hey. I want to work on this. Please assign it to me.

**Comment by factscub** [comment]
all properties in the custom object are mandatory ?
