### ISSUE TITLE
Generate styles in css files rather than `useStore.js` file

### ISSUE THREAD

**Issue by cruxcode** [Atri-Labs/atrilabs-engine#270]
Explanation:
Generating CSS in the `useStore.js` file has the following drawbacks:
1. Cannot write media queries.
2. Handling breakpoint-related styling in javascript is tricky.
3. Javascript becomes heavy.
4. The event data that is sent to the server, contains styles as it's populated in `useStore.js`. This makes the network payload huge (in the scale of 16KB+). This poses a lot of problems, such as express framework allows 16KB payload size by default for JSON payloads.

**Comment by darshitac11** [comment]
@all-contributors please add @cruxcode for question, bug, ideas
