### ISSUE TITLE
Component Navigator

### ISSUE THREAD

**Issue by cruxcode** [Atri-Labs/atrilabs-engine#34]
Explanation:

Component Navigator can be used as an escape hatch for many of the shortcomings in the UX of the canvas.

**Comment by cruxcode** [comment]
# Signature of Component Navigator component

```typescript
import React from "react";

export type ComponentNode = {
  type: "acceptsChild" | "normal";
  id: string;
  name: string;
  children: ComponentNode[];
  open: boolean;
};

export type ComponentNavigatorProps = {
  rootNode: ComponentNode;
  // Call onChange everytime the selected node is repositioned
  onChange: (change: { id: string; parentId: string; index: number }) => void;
  // Call onHover everytime user hovers over a component
  onHover: (id: string) => void;
  // Call onSelect everytime user clicks on a component
  onSelect: (id: string) => void;
  // Call onDragStart whenever the drag process starts
  onDragStart: (id: string) => void;
  // Call onDragEnd whenever the drag process stops
  onDragEnd: (id: string) => void;
};

export const ComponentNavigator: React.FC<ComponentNavigatorProps> = (
  props
) => {
  return <div></div>;
};
```

# Interactions

- Slide up/down i.e. mouse down and move vertically
  - The selected node will be re-positioned to the nearest open parent
- Move left
  - Guard - If the selected node is currently the last component of its parent
  - The selected component will be attached at the end of the grandparent
  - Move left once every `10px`
- Move right
  - Guard - If the selected node is currently the last component of its parent & the previous sibling is of type `acceptsChild`
  - The selected component will be attached at the end of the `previousSibling`
  - Move right once every `10px`

## Notes

- Use XState
- After every reposition, set horizontal measurement to `0px`

**Comment by cruxcode** [comment]
Component navigator can be opened by clicking on icon ![comp-nav-icon](https://user-images.githubusercontent.com/30747788/191412887-3c9aecc4-065d-4e79-8945-82c6158cb529.svg) on the top left menu.

**Comment by cruxcode** [comment]
Colors:

- Selected component's background color - #1F2937 (gray800)
- Selected component's text color - #6B7280 (gray500)
- Normal text color - #D1D5DB (gray300)

**Comment by melvinodsa** [comment]
I will take it up

**Comment by darshitac11** [comment]
@all-contributors please add @melvinodsa  for code
