### ISSUE TITLE
Add a Readme file in Atri-Apps

### ISSUE THREAD

**Issue by darshitac11** [Atri-Labs/atrilabs-engine#371]
## What to include in Readme:

Suggestion 1: Follow the format below 👇 

Check out all the apps that have been built and deployed using [Atri framework](https://github.com/Atri-Labs/atrilabs-engine). 

| App title                            | Website                               | Details                               |
| ------------------------------- | --------------------------------------- | --------------------------------------- |
| **Personal blog**             | [Website link](https://atri-apps.github.io/personal_blog/)                  | [GitHub repository](https://github.com/Atri-Apps/personal_blog)                 |
| **Ecommerce website** | [Website link](https://atri-apps.github.io/personal_blog/)                   | [GitHub repository](https://github.com/Atri-Apps/personal_blog)            |
| **Background remover app**         | [Website link](https://atri-apps.github.io/personal_blog/) | [GitHub repository](https://github.com/Atri-Apps/personal_blog)               |

**Comment by darshitac11** [comment]
@cruxcode, @sanskarg348 - what do you think? 

I've created this issue because our current organization looks like below:  

<img width="938" alt="Screen Shot 2022-10-11 at 8 44 45 AM" src="https://user-images.githubusercontent.com/102641692/195094093-e61cd98a-7c31-4cd5-9afb-cb3d63f5edf5.png">

To review the apps, visitors need to go to each repository and check it out. A Readme structure like suggested above will help us in sharing more information quickly.

**Comment by darshitac11** [comment]
@sanskarg348 - links appear to be broken here. E.g. ecommerce website is taking me to personal blog website

**Comment by sanskarg348** [comment]
Looking into it Ma'am

**Comment by sanskarg348** [comment]
Fixing it i actually copied the reference table that had interchanged links pushing the fixed readMe now
