### ISSUE TITLE
Review fix for all contributors bot

### ISSUE THREAD

**Issue by darshitac11** [Atri-Labs/atrilabs-engine#372]
See the error here: https://github.com/Atri-Labs/atrilabs-engine/issues/366#issuecomment-1274540137

Refer this for solution: https://github.com/all-contributors/all-contributors/issues/445

Let me know if you need more details.

**Comment by adityaxpique** [comment]
Ma'am I noticed that you've written `https://github.com/all-contributors please add @grishamg as a contributor for bug report`, but in the docs example it's like `https://github.com/all-contributors please add @grishamg for bug report`

**Comment by darshitac11** [comment]
Don't think that'll work either since the bot is not stringent on syntax:

please add @grishamg for bug report

**Comment by adityaxpique** [comment]
Okay I'll look further into it then.

**Comment by adityaxpique** [comment]
Ma'am we have a all-contributorsrc file and in docs it's mentioned that it should be a JSON file but in the repo it isn't .json specifically. This might be the reason.

**Comment by adityaxpique** [comment]
In line no 23 there's a missing closing inverted comma. 

![Image](https://user-images.githubusercontent.com/56078748/195580151-3eceb7f0-4196-4777-b3f2-46c5c6feb756.png)

**Comment by darshitac11** [comment]
But this file was autogenerated when I had installed the app. 

For your reference, when the bot is evoked, it opens a PR. When the PR is resolved, the app makes 3 changes :
- adds a dictionary in allcontributor src
- updates table in readme
- updates count in the badge in readme

**Comment by darshitac11** [comment]
I started getting this error since I resolved some of the conflicts in the PR by making changes to these files manually.

**Comment by darshitac11** [comment]
Deleted the app and reinstalled it - seems to be working alright now
