### ISSUE TITLE
Inform users when socket connection breaks

### ISSUE THREAD

**Issue by cruxcode** [Atri-Labs/atrilabs-engine#385]
Explanation:

Users are unaware of whether the server is running in the terminal. This might lead to losing work due to unsaved events.

Solution:
Show server status on the left bottom menu. Also, show the steps to take when a problem occurs.

**Comment by cruxcode** [comment]
## Implementation

1. Show an error when the connection between the browser & event server breaks.
2. The browser connects to the IPC server as well.
3. The IPC server informs the browser over the socket connection about the health of the services: `publish_server`, `atri_cli`.

**Comment by harishfalco** [comment]
@cruxcode I can work on this.

**Comment by cruxcode** [comment]
> @cruxcode I can work on this.

@harishfalco sorry but I am already half way through this issue. I will discuss with you on some other issues in our [Slack Community Channel](https://join.slack.com/t/atricommunity/shared_invite/zt-1e756m1at-bZBxngvw7KWWO0riI4pc0w).

I really appreciate your interest in contributing to this repo.

**Comment by darshitac11** [comment]
Suggestions:

1. Change error message

- Suggested error message when server is disconnected: "Your server has been disconnected. Please run `atri start` in your shell again."
- Current message: "Please stop current atri process and run atri start in your shell again."

2. When the disconnect popup appear, the editor should be dimmed so that the message is more prominent and hard to miss.

**Comment by cruxcode** [comment]
@darshitac11 I don't want to dim the editor, in other words, I want the editor to be functional, although the events won't be recorded in the backend. This will help user to copy paste things from an existing project (with closed server) to another project (whose server is running).

**Comment by darshitac11** [comment]
Ah yes - make sense! Sorry to have missed this - this functionality would be helpful for sure. We shouldn't work on suggestion no. 2.

What about suggestion no. 1?

**Comment by cruxcode** [comment]
@darshitac11 I have published version `v0.0.75` with the old error message. Will apply your suggested message in the next version.
