### ISSUE TITLE
🐞  Changes are being undone across breakpoints (Reponsivenes)

### ISSUE THREAD

**Issue by sanskarg348** [Atri-Labs/atrilabs-engine#388]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behaviour

When we change a property in desktop mode and switch to tablet mode and change a property and try to undo it it also undoes the changes in desktop mode and previews them in tablet mode

### Expected Behavior

Desktop changes should only be reversed in desktop mode and same for tablet and mobile mode

### System configuration

```markdown
1. OS: macOS
2. Bits: 
3. Browser: Google Chrome
4. Atri framework version: 0.0.67
5. Virtual environment: pipenv
```

**Comment by cruxcode** [comment]
## Approach

Ensure that when a redo is applied, the CSS properties are applied to the breakpoint they were previously applied to.
