### ISSUE TITLE
🐞 Redo works even after performing some new action after performing undo

### ISSUE THREAD

**Issue by adityaxpique** [Atri-Labs/atrilabs-engine#389]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Suppose I have two components on screen now I copy one and paste it several times, then I undo that action, now I select other component and copy paste it several times, now I undo the copy paste, when I redo the copy paste and continue pressing redo, the older components appear between the new components. I don't know if it's expected behavior or not. I've attached the link to the recording demonstrating the above written steps too.

### Screenshots

https://www.loom.com/share/3ccd0cadb9d54131ba9fbf36cf652906

### Expected Behavior

The redo action should not work after some new action is performed after undoing.

### System configuration

```markdown
1. OS: [Windows 11]
2. Bits: [64 bit]
3. Browser: [Google Chrome]
```

**Comment by darshitac11** [comment]
Google Doc:
1
2
3
4
Undo 4
5
Redo 5

-----
Current:
1
2
3
4
Undo 4
5
Redo 4

Current:
1
2
3
4
Undo 4
Undo 3
Redo 3
Redo 4

-----
Planned:
1
2
3
4
Undo 4
5
No Redo since undo cycle has broken

**Comment by cruxcode** [comment]
Approach:

Clean the redo stack after any event that doesn't have the name `UNDO_REDO_EVENT`.
