### ISSUE TITLE
Add a `Modal` component

### ISSUE THREAD

**Issue by darshitac11** [Atri-Labs/atrilabs-engine#430]
### Discussed in https://github.com/Atri-Labs/atrilabs-engine/discussions/410

<div type='discussions-op-text'>

<sup>Originally posted by **sanskarg348** October 16, 2022</sup>
The following link refers to the Modal component of react-bootstrap

https://react-bootstrap.github.io/components/modal/
</div>

**Comment by jonathanalvares9009** [comment]
- [ ] Learn how modal is used and how it is implemented in other frameworks
- [ ] Learn the prerequisites (if any)
- [ ] Create a prototype for modal
- [ ] Create the final version for modal

**Comment by jonathanalvares9009** [comment]
@darshitac11 could I get a little more clarity over what's needed in the modal. Like any modal in particular that can be taken as reference as the above link has many modals with tiny customisations. So what's needed for our implementation
