### ISSUE TITLE
Create a welcome bot for Slack community

### ISSUE THREAD

**Issue by darshitac11** [Atri-Labs/atrilabs-engine#436]
1. The welcome bot introduces newcomers to different channels and the recommended activity in each. 
2. It also shares relevant resources such as: 
- FAQs about installation: https://github.com/Atri-Labs/atrilabs-engine/discussions/categories/help-installation-start
- Cheatsheet of keyboard shortcuts for Atri editor: https://github.com/Atri-Labs/atrilabs-engine/discussions/412

## References: 
https://github.com/slack-samples/deno-welcome-bot

https://api.slack.com/tutorials/tracks/create-bot-to-welcome-users

**Comment by jonathanalvares9009** [comment]
- [ ] Create a bot that can send messages
- [ ] Create a bot that triggers when a member joins a channel
- [ ] Create a bot that sends messages over DM
- [ ] Optimise the prototype
- [ ] Final bot

**Comment by darshitac11** [comment]
Welcome message 

----


Hi username 👋,

Welcome to the Atri community! We are so excited to have you here 🥰

Please check the frequently asked questions below:

- [Installation](https://github.com/Atri-Labs/atrilabs-engine/discussions/categories/help-installation-start)
- [General Resources](https://github.com/Atri-Labs/atrilabs-engine/discussions)

Check out the channels below to connect with everyone here:

- [#introductions](https://atricommunity.slack.com/archives/C03TJHWSA2F) - we’d love to get to know you better!
- [#queries](https://atricommunity.slack.com/archives/C03TJPYR2E7) - ask questions about the Atri framework here
- [#resources](https://atricommunity.slack.com/archives/C03TJT3NZU2) - find resources to make the best use of the Atri framework
- [#gallery](https://atricommunity.slack.com/archives/C03TXAAENGZ) - share your apps here
- [#random](https://atricommunity.slack.com/archives/C03TJM05DB4) - anything else

If you have any questions or suggestions, feel free to DM the community organizers - [@Darshita](https://atricommunity.slack.com/team/U03U8C5M9UG) or [@Shyam Swaroop](https://atricommunity.slack.com/team/U03U8C7KDHN).
