### ISSUE TITLE
🐞 Cursor jumps to the end of the string in custom panel

### ISSUE THREAD

**Issue by darshitac11** [Atri-Labs/atrilabs-engine#481]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Current Behavior

1. Suppose I have already provided the text that should appear in a Textbox component as `New text`. 
2. I now want to edit the first word. So I click before `N` to activate the cursor at that location such that I see the following: `|New text`. 
3. As I enter the first character `A`, the cursor jumps to the end of the string which is not the expected behavior. `ANew text|`. 

### Screenshots

https://www.loom.com/share/079f7951a96f42ed90bbe5ce7fc7c510

### Expected Behavior

At Step 3, the cursor should still be available after the new character `A` like this `A|New text`. 

### Steps To Reproduce

```markdown
Video & current behavior has the reproduction steps.
```

### Anything else?

I believe this issue was raised earlier but I can't find it now - maybe it was closed or never added in `Issues`.

**Comment by cruxcode** [comment]
@adityaxpique Currently we do not have `ControlledInput` in customs layer. Please make a `ControlledInput` for customs panel (similar to what we have for styles panel) and use it for all the components in custom panel.

**Comment by adityaxpique** [comment]
Okay sir, I'll do that.
