### ISSUE TITLE
Improve chart components

### ISSUE THREAD

**Issue by darshitac11** [Atri-Labs/atrilabs-engine#488]
- [x] Charts have a lot of left padding which makes it different to align them properly
<img width="413" alt="Screen Shot 2022-10-29 at 2 41 27 PM" src="https://user-images.githubusercontent.com/102641692/198847809-e958fd61-26bf-4289-9ae9-42274686cda5.png">

- [x] Change font of legend, tooltip and axes to `IBM Plex Sans`
- [x] Center align legend wrt chart

**Comment by jonathanalvares9009** [comment]
@darshitac11 and @cruxcode the first sub issue, we have to give a width so that it snaps into place. It's apparently a bug in Recharts. https://github.com/recharts/recharts/issues/843#issuecomment-347637995 this one worked

**Comment by darshitac11** [comment]
Got it, thanks! 

We'll provide this width as a hack in the default state of components, right? Or will we leave it on the app creators to make this adjustment?

**Comment by jonathanalvares9009** [comment]
@darshitac11 what I found is anything above 60 has this padding. So if we leave it to the app creators this might reappear but I also feel we should let them decide what to do.

**Comment by cruxcode** [comment]
@darshitac11 for the font, wouldn't it be better if whatever font we apply to the chart gets applied instead of hard coding IBM Plex Sans?

**Comment by darshitac11** [comment]
My suggestion was to add `IBM Plex Sans` as default. Users can still override it.
