### ISSUE TITLE
🐞 No CSS unit defined during adding margin and padding to the any of component 

### ISSUE THREAD

**Issue by awdhesh-kumar27** [Atri-Labs/atrilabs-engine#495]
![Screenshot (196)](https://user-images.githubusercontent.com/100534409/198894190-d3a43e78-99e4-4771-bdd8-2dfae083f903.png)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There is no specific css units during adding margin and padding to any of the component by default px is working but it is good but more css units are available and they help in making component more responsive by default.

### Screenshots

[](url)

### Expected Behavior

More css units like : px, % , rm etc

### System configuration

```markdown
1. OS: [e.g. macOS Monterey 12.6]
2. Bits: [e.g. 64 bit]
3. Browser: [e.g. Google Chrome]
4. Atri framework version: [e.g. 0.0.64]
5. Virtual environment: [e.g. pipenv]
```

**Comment by awdhesh-kumar27** [comment]
![Screenshot (196)](https://user-images.githubusercontent.com/100534409/198894169-0b063a19-ef8f-40e6-8807-a3a4e4a0fa46.png)

**Comment by darshitac11** [comment]
Thanks for the suggestion but it's not a bug. We have only provided `px` at the moment but we'll include other units in future.

**Comment by cruxcode** [comment]
@adityaxpique can we use the same size input box here? I guess you will be able to complete this task fast, hence, assigning you.
