### ISSUE TITLE
🐞 Box shadow is not being applied

### ISSUE THREAD

**Issue by darshitac11** [Atri-Labs/atrilabs-engine#498]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

- Box shadow color pop-up does not allow moving the color picker to change color. However, the hex code can be pasted.
- After `Build and Run`, box shadow is not applied.
- Upon visiting the style panel again, the Y-offset, blur and spread are overwritten to `0 px`. 

### Screenshots

https://www.loom.com/share/5d75c3b7f75d4e34ba9b393f57e731d4

### System configuration

```markdown
1. OS: macOS Monterey 12.6
2. Bits: 64 bit
3. Browser: Google Chrome
4. Atri framework version: 0.0.78
5. Virtual environment: pipenv
```

**Comment by DivyMani01** [comment]
![Screenshot 2022-12-31 170155](https://user-images.githubusercontent.com/120504738/210135264-7fbedd65-453c-4bdd-8b6a-d47ffe98b5e4.png)
