### ISSUE TITLE
🐞 Atri Visual Editor to Actual Website Position difference 

### ISSUE THREAD

**Issue by wereign** [Atri-Labs/atrilabs-engine#523]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I add elements with great width, I have to offset elements to the right of the center line.
This lets the element be in the center when I actually build and run the website

### Screenshots

![1](https://user-images.githubusercontent.com/101888489/200160308-fa139085-26af-4c2c-9902-305b16ce2e20.png)

The above image shows the elements to the far right in the editor.

![2](https://user-images.githubusercontent.com/101888489/200160314-89bf186f-3cff-4544-9db2-962045625910.png)

This image shows that after building the website the elements are towards the center.

### Expected Behavior

A high similarity between simulation and the real build

### System configuration

```markdown
1. OS: [Ubuntu 20.04]
2. Bits: [64 bit]
3. Browser: [Google Chrome]
4. Atri framework version: [0.0.64]
5. Virtual environment: [pipenv]
```

**Comment by cruxcode** [comment]
This is expected as you are using CSS in the wrong way. Please refer to [this](https://www.youtube.com/watch?v=HZJ5cSSY22I&list=PLTQwOMNg4n8DnA_VC-5J_OSEUWxEHTdXR) video series to know more about how to use CSS correctly.
