### ISSUE TITLE
Apply visual hints for hover & select.

### ISSUE THREAD

**Issue by cruxcode** [Atri-Labs/atrilabs-engine#677]
## Steps

1. Study the old implementation of the state machine to implement it in the new `canvasMachine`. The old machine implementation can be found [here](https://github.com/Atri-Labs/atrilabs-engine/blob/main/packages/canvas-runtime/src/decorators/CanvasActivityDecorator.tsx#L478-L768).
2. First study how the `hover` state has been implemented. The user can move from one component to another. When user scrolls the hover state is exited. Similarly when the user goes outside the canvas, the hover state is exited.

## Current Implementation

1. Start working in the `ready` state.
2. Note that we have to use `mousemove` event on `window` in capture phase.

## Tasks
- [x] #686
- [x] #693

**Comment by jonathanalvares9009** [comment]
- [ ] Create hover and select states
- [ ] Create reposition state
