### ISSUE TITLE
Add icons for components

### ISSUE THREAD

**Issue by darshitac11** [Atri-Labs/atrilabs-engine#69]

**Comment by cruxcode** [comment]
Unable to download asset for
1. Button
2. Input
3. Menu
4. Text

Missing icon for:
1. Carousel
2. Countdown
5. Flex 
6. Link
7. Radio
8. Slider
9. Toggle
10. Upload

**Comment by cruxcode** [comment]
width = 56px
height = 24px

**Comment by darshitac11** [comment]
Resized 1st set of icons

**Comment by darshitac11** [comment]
All icons available in the frame icons-editor

**Comment by cruxcode** [comment]
Chart Icons not downloadable -
1. Line Chart
2. Bar Chart
3. Histogram
4. Candlestick
5. Scatter
6. Area
7. Pie

**Comment by darshitac11** [comment]
Added in the same frame
