### ISSUE TITLE
The python-socketio connection closes after some time

### ISSUE THREAD

**Issue by cruxcode** [Atri-Labs/atrilabs-engine#71]

**Comment by cruxcode** [comment]
Solved in `v00.62`. We can re-open this issue if the problem resurfaces. As per socketio-server documentation, if the payload is large, the `intervalTime` must be increased.

**Comment by darshitac11** [comment]
Seems like this

**Comment by cruxcode** [comment]
@darshitac11 referring to the snapshot, since `atri` was running I am assuming user was inside the `conda` virtual environment, but I infer that the user doesn't have python installed in the `conda` environment. The `atri` python cli assumes that the command `python` will be available inside the environment.

I can handle this case that if `python` isn't available then also all other functions of the `atri start` command keep running smoothly.
