### ISSUE TITLE
Create a `<iframe>` component

### ISSUE THREAD

**Issue by cruxcode** [Atri-Labs/atrilabs-engine#741]
Create an `iframe` component. The signature for `iframe` component looks as follows:

Write the component in `packages/react-component-manifests/src/manifests/IFrame/IFrame.tsx`. The code will look something like this -
```jsx
const IFrame = React.forwardRef((props, ref)=>{
 // Provide all options avaliable in an iframe
  return <iframe  className={props.className} ref={ref} styles={props.styles} src={props.href} srcdoc={props.srcdoc} />
})

export default IFrame;
```

Then write the component manifest in `packages/react-component-manifests/src/manifests/IFrame/IFrame.manifests.tsx`. The code will look something like this -
```jsx
import {createComponentManifest} from "@atrilabs/utils";

export default createComponentManifest({name: "IFrame"});
```

Pre-requisites:

1. Setup a fork of this repo as discussed in [CONTRIBUTING.md](https://github.com/Atri-Labs/atrilabs-engine/blob/91357d393bfb9e53bfeb0a36f7268c0a1bdf425a/CONTRIBUTING.md).
2. Read this discussion https://github.com/Atri-Labs/atrilabs-engine/discussions/169

**Comment by subhajit20** [comment]
@cruxcode  hey! I want to work on this issuse... can You assign it to me ?

**Comment by subhajit20** [comment]
@cruxcode  how do I get lerna bootstrap ?

**Comment by subhajit20** [comment]
@cruxcode  hello! whenever I run the step no 8 build 
it throws a error

```
subhajit@Mac-Solutions-MacBook-Pro pwa-builder % yarn build
yarn run v1.22.19
$ concurrently "yarn build-editor" "yarn build-manifest-registry"
$ build-editor -i "@atrilabs/pwa-builder-manager:@atrilabs/design-system:@atrilabs/forest:@atrilabs/app-design-forest:@atrilabs/utils"
$ build-manifest-registry
[0] chmod: /Users/subhajitghosh/Documents/open-source/atrilabs-engine/packages/commands/dist/build-editor.js: No such file or directory
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[0] yarn build-editor exited with code 1
[1] chmod: /Users/subhajitghosh/Documents/open-source/atrilabs-engine/packages/commands/dist/build-manifest-registry.js: No such file or directory
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[1] yarn build-manifest-registry exited with code 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
subhajit@Mac-Solutions-MacBook-Pro pwa-builder % 
```

**Comment by subhajit20** [comment]
@cruxcode  hello! I have pretty much done all the stuff on this issue.
Should I make a pr?

**Comment by subhajit20** [comment]
@cruxcode Hello! I am working on this issue.

**Comment by subhajit20** [comment]
@cruxcode  can you assign it to me ?

**Comment by balogunkeji** [comment]
I am currently working on it

**Comment by cruxcode** [comment]
Done!
