### ISSUE TITLE
Issue while adding DropDown , error says :TypeError: Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by AbbhilashR** [Atri-Labs/atrilabs-engine#747]
I have placed a DropDown and the values for it are assigned in the main.py file , but when i build and publish the project it throws this error:
![image](https://user-images.githubusercontent.com/112764493/229084978-74a6dc74-d555-4071-abf2-cae986dc9693.png)

I am also attaching my main.py below for your reference 
![image](https://user-images.githubusercontent.com/112764493/229085270-628a34d6-c25f-4f84-828e-cf9cd5b25e51.png)

**Comment by cruxcode** [comment]
Hi @AbbhilashR, thanks for reporting the bug. We have fixed the bug in new version and will be released in 2 weeks. Sorry for the delay.

**Comment by cruxcode** [comment]
Fixed in version 1.0.0-alpha15
