### ISSUE TITLE
Add box-sizing to style panel

### ISSUE THREAD

**Issue by cruxcode** [Atri-Labs/atrilabs-engine#86]
Explanation:

In case we provide a component `width: 100%` and if this component has `padding: 20px`, then, this component's effective height will be `100% + 40px`. This can be prevented with `box-sizing: border-box` as it includes border and padding in the width.

**Comment by adityaxpique** [comment]
added box-sizing, icons need to be corrected

**Comment by cruxcode** [comment]
Great work!
