### ISSUE TITLE
The order of styles property in properties tab is not intuitive

### ISSUE THREAD

**Issue by cruxcode** [Atri-Labs/atrilabs-engine#9]
Explanation:
Currently, typography comes on top and flex, flex child comes at the bottom.

Fix:
Change the order in `@atrilabs/component-style-layer` package.

**Comment by cruxcode** [comment]
@darshitac11 can you propose an order for styles property?

**Comment by cruxcode** [comment]
Currently available categories are:
- Typography
- Size
- Border
- Layout (parent)
- Flex Child
- Position
- Spacing

**Comment by darshitac11** [comment]
Layout (parent)
Flex Child
Spacing
Size
Border
Typography
Position

**Comment by cruxcode** [comment]
Forgot to mention Background in the list. I am putting Background second last (before Position). I am closing this issue with this change, if you want to recommend some other order please re-open this issue.

**Comment by darshitac11** [comment]
Since border is part of the box model, let's use this order instead: 

- Layout (parent)
- Flex Child
- Size
- Spacing
- Border
- Typography
- Background
- Position
